### ISSUE TITLE
No toolchain after 19.1.0 can be downloaded

### ISSUE THREAD

**Issue by arvid-norlander** [bazel-contrib/toolchains_llvm#417]
```bazel
bazel_dep(name = "toolchains_llvm", version = "1.2.0")
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    llvm_version = "19.1.0",
)
use_repo(llvm, "llvm_toolchain")
```

works, but this does not:

```bazel
bazel_dep(name = "toolchains_llvm", version = "1.2.0")
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    llvm_version = "19.1.3",
)
use_repo(llvm, "llvm_toolchain")
```

Yet https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.3 is the most recent release as of writing this. The error is as follows:

```
INFO: Repository toolchains_llvm~~llvm~llvm_toolchain_llvm instantiated at:
  <builtin>: in <toplevel>
Repository rule llvm defined at:
  /home/USER/.cache/bazel/_bazel_USER/01afa9c2444d0e5461c9c78c1470582d/external/toolchains_llvm~/toolchain/rules.bzl:27:23: in <toplevel>
ERROR: An error occurred during the fetch of repository 'toolchains_llvm~~llvm~llvm_toolchain_llvm':
   Traceback (most recent call last):
        File "/home/USER/.cache/bazel/_bazel_USER/01afa9c2444d0e5461c9c78c1470582d/external/toolchains_llvm~/toolchain/internal/repo.bzl", line 311, column 35, in llvm_repo_impl
                updated_attrs = _download_llvm(rctx)
        File "/home/USER/.cache/bazel/_bazel_USER/01afa9c2444d0e5461c9c78c1470582d/external/toolchains_llvm~/toolchain/internal/llvm_distributions.bzl", line 617, column 56, in download_llvm
                urls, sha256, strip_prefix = _distribution_urls(rctx)
        File "/home/USER/.cache/bazel/_bazel_USER/01afa9c2444d0e5461c9c78c1470582d/external/toolchains_llvm~/toolchain/internal/llvm_distributions.bzl", line 660, column 13, in _distribution_urls
                fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: LLVM-19.1.3-Linux-X64.tar.xz
Please ensure file name is correct.
ERROR: no such package '@@toolchains_llvm~~llvm~llvm_toolchain_llvm//': Unknown LLVM release: LLVM-19.1.3-Linux-X64.tar.xz
Please ensure file name is correct.
ERROR: /home/USER/.cache/bazel/_bazel_USER/01afa9c2444d0e5461c9c78c1470582d/external/toolchains_llvm~~llvm~llvm_toolchain/BUILD.bazel:203:14: @@toolchains_llvm~~llvm~llvm_toolchain//:clang-tidy depends on @@toolchains_llvm~~llvm~llvm_toolchain_llvm//:bin/clang-tidy in repository @@toolchains_llvm~~llvm~llvm_toolchain_llvm which failed to fetch. no such package '@@toolchains_llvm~~llvm~llvm_toolchain_llvm//': Unknown LLVM release: LLVM-19.1.3-Linux-X64.tar.xz
Please ensure file name is correct.
```

Looking at it, I don't think they changed the naming scheme, but something clearly broke.

**Comment by jwbee** [comment]
Is this just because the artifacts trickle in after the fact? It looks like the archive is there now, for 19.1.3.

For ARM the situation is worse. The last upstream release with linux-aarch64 binaries is 18.1.8.

**Comment by jwbee** [comment]
Ah no, I see the issue: you are using this repo at v1.2.0 but the compiler you want is newer! You need to use toolchains_llvm at master or the master commit to get those newer archives.

**Comment by arvid-norlander** [comment]
Ah I see, I would have assumed I could use the latest version of LLVM, since the upstream archives follow a predictable naming scheme. I guess the reason then is to handle checksums? What is the release cadence of this repo?

**Comment by helly25** [comment]
Version 19.1.7 is available as of https://github.com/bazel-contrib/toolchains_llvm/pull/461
